services:
  # A Docker web service
  - type: web
    name: face-recognition-service
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile  
    autoDeploy: true
    buildCommand: docker build -t face-recognition-service .
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
